### ISSUE TITLE
Use of unresolved identifier 'Inceptionv3' Error

### ISSUE THREAD

**Issue by WillRRRR** [hanleyweng/CoreML-in-ARKit#2]
<img width="1152" alt="screen shot 2017-07-29 at 11 23 07 am" src="https://user-images.githubusercontent.com/30376565/28746354-64fcc2ec-7450-11e7-8c3c-bb4e7e619efc.png">

**Comment by hanleyweng** [comment]
Please see instructions in readme

"You'll have to download "Inceptionv3.mlmodel" from Apple's Machine Learning page, and copy it into your XCode project."

**Comment by LwsBtlr** [comment]
I've copied it in (appears in the list just under Info.plist just like in the list) but I am getting this error and another with the Xcode GM. (downloaded incpetion3 within he last few minutes

![screenshot 2017-09-18 05 35 49](https://user-images.githubusercontent.com/1143150/30540182-43b54c5c-9c33-11e7-9c3e-42eb2b8438fd.png)

**Comment by hanleyweng** [comment]
Hi @LwsBtlr 

~~From your screenshot, it seems like your filenames don't match up. ("….mlmodel")~~
Update: Oops, nvm, that seems correct.

A few things may've changed since the GM - e.g. it seems that the ARWorldTrackingSessionConfiguration may have been renamed 'ARWorldTrackingConfiguration'.
– src: https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration

Beyond this: it seems like there may be a few issues with the currrent XCode 9 GM. It might be worth waiting for the next version for now, or try reverting to an earlier beta version. For reference, this version of the code was Written in: XCode 9 beta 3 (9M174d).

**Comment by LwsBtlr** [comment]
I don't have access to the earlier betas since I waited for the GM to install Xcode 9, so waiting for the next versions sounds like the best plan. Thanks.
